### ISSUE TITLE
Failure to create anchors for bullet list?

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma-ogc#828]
Is this a known issue / limitation?

https://github.com/opengeospatial/ogcapi-common/commit/9507e589f9db4d7b4bae0c88b9f16ab0bad07556

Thanks!

**Comment by jerstlouis** [comment]
@opoudjis 

> I get these missing anchors:

I have fixed all of those other errors in the subsequent commits. Those have nothing to do with the glossary, they were either missing bibliographic references that I added or mismatched section anchors, except for the `recomendation-defntion` which was a typo in the glossary.

> It is absolutely true that bulleted lists are not recognised as terms, and Metanorma will complain about that,

The issue I was reporting is that Metanorma complains about "Unresolved ID reference" if those terms are inside bullet list.
I have no idea what an "Unresolved ID reference" is -- I assumed it had to do with the anchors not working inside bullet list, because it gave identical errors for those wrong "anchors" references. I'm not sure those errors have anything to do with "terms", since this glossary is not the "Terms and definition" section (3), but a separate annex.

If I just add the `*` back in front of each of the bold terms from the head of the `master` branch I get:

```
Page 4: Unresolved ID reference "requirements-class-definition" found.
Page 4: Unresolved ID reference "ctc-definition" found.
Page 5: Unresolved ID reference "rc-collections" found.
Page 5: Unresolved ID reference "rc-html" found.
Page 5: Unresolved ID reference "rc-json" found.
Page 5: Unresolved ID reference "rc-umd-collection" found.
Page 5: Unresolved ID reference "requirements-class-definition" found.
Page 5: Unresolved ID reference "ctc-definition" found.
Page 12: Unresolved ID reference "ctc-definition" found.
Page 17: Unresolved ID reference "ctm-definition" found.
Page 17: Unresolved ID reference "requirement-definition" found.
Page 17: Unresolved ID reference "requirements-module-definition" found.
Page 83: Unresolved ID reference "ctm-definition" found.
Page 83: Unresolved ID reference "recommendation-definition" found.
Page 83: Unresolved ID reference "ctc-definition" found.
Page 83: Unresolved ID reference "requirement-definition" found.
Page 84: Unresolved ID reference "recommendation-definition" found.
Page 84: Unresolved ID reference "standardization-target-definition" found.
Page 84: Unresolved ID reference "requirement-definition" found.
11 link targets could not be fully resolved and now points to the top of the page or are dysfunctional.
```

However, it seems like clicking the links to these glossary items still work, which I had not realized ( I thought they didn't, perhaps because the first 3 items all point to "Conformance Test Module" so I thought they were broken anchors ).

In any case, this was a very head-scratching situation. I'm happy to hear that I've resolved this the correct way, but what we had causing the errors is how @ghobona had originally converted this glossary to metanorma back in November. And there still seems to be a peculiarity related to anchors to bullet list items causing these puzzling "Unresolved ID reference errors".

**Comment by opoudjis** [comment]
OK, but like I said, I could not replicate what you were getting with the list items: when I put the list items back in, I was getting the unresolved anchors that you subsequently fixed, not the errors on the list item anchors. What is true is that {{}} links are only going to work if the destination is recognised as a term—which they won't be if it is a list item; but your document did have <<>> not {{}}, so that was not an issue.

Could you provide me with a clean document generating those errors, so I can try and work out what else might have happened?

**Comment by jerstlouis** [comment]
@opoudjis Like I said you can just add the bullets in front to reproduce the errors.

Just patch the latest at https://github.com/opengeospatial/ogcapi-common/tree/master/collections (20-024.adoc) with:

[annex_glossary.adoc.txt](https://github.com/user-attachments/files/21563818/annex_glossary.adoc.txt)

```
Page 4: Unresolved ID reference "requirements-class-definition" found.
Page 4: Unresolved ID reference "ctc-definition" found.
Page 5: Unresolved ID reference "requirements-class-definition" found.
Page 5: Unresolved ID reference "ctc-definition" found.
Page 12: Unresolved ID reference "ctc-definition" found.
Page 17: Unresolved ID reference "ctm-definition" found.
Page 17: Unresolved ID reference "requirement-definition" found.
Page 17: Unresolved ID reference "requirements-module-definition" found.
Page 87: Unresolved ID reference "ctm-definition" found.
Page 87: Unresolved ID reference "recommendation-definition" found.
Page 87: Unresolved ID reference "ctc-definition" found.
Page 87: Unresolved ID reference "requirement-definition" found.
Page 88: Unresolved ID reference "recommendation-definition" found.
Page 88: Unresolved ID reference "standardization-target-definition" found.
Page 88: Unresolved ID reference "requirement-definition" found.
7 link targets could not be fully resolved and now points to the top of the page or are dysfunctional.
```

**Comment by opoudjis** [comment]
@jerstlouis I am sorry it is taking me so long to get back to this, but I have a lot on (as you can see in https://github.com/orgs/metanorma/projects/15/views/8 — and in fact, the 14 urgent issues still there are meant to be take priority over this). But I am trying to remove backlog.

... I ran the latest version of 20-024.adoc, replacing annex_glossary.adoc with the file you provided. 

I did not get the errors you are reporting, and the missing anchors you report are compiling in my version to

```
<ul id="ctc-definition" anchor="ctc-definition" semx-id="_680dc9bb-4f09-5cec-dd6d-56a03695ef52">

<ul id="requirements-class-definition" anchor="requirements-class-definition" semx-id="_2c15263c-b17b-1b26-f633-55f9294ca919">

<ul id="ctm-definition" anchor="ctm-definition" semx-id="_00436aa2-1e66-d589-6dd3-235a0e6a61d6">

<ul id="requirement-definition" anchor="requirement-definition" semx-id="_c5e56645-9fd5-4c2b-252d-e2e09887aad5">
```

etc: all of them are pointing to defined ordered lists (not  list items). It is rendering as a list, errors are not being reported for those anchors, and the links work:


<img width="1285" height="1106" alt="Image" src="https://github.com/user-attachments/assets/34e6ac6b-040a-4c6a-beed-1755fe60611a" />


Your compilation used code dating from June 23, and I was already failing to replicate it with a code release from a month later, with no obvious change to explain it. So I still do not understand what is going on.

There is one piece of information which I didn't highlight, though I did report it before in passing: the anchor is not specific to a single list item, but concerns an entire list. If you are doing some sort of processing which removes the list wrapper, that anchor would go away; but the anchors are still there.

Of course, what you have provided is:

```
[[requirements-class-definition]]
* *Requirements Class* +
aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class (<<ogc08-131r3,OGC 08-131r3>>)

[[requirements-module-definition]]
* *Requirements Module* +
aggregate of <<requirement-definition,requirements>> and <<recommendation-definition,recommendations>> of a specification against a single <<standardization-target-definition,standardization target>> type (<<ogc08-131r3,OGC 08-131r3>>)
```

The addition of an anchor before the list item is resulting in Asciidoctor parsing  it as a distinct list, and not a list item within the same list.  But I don't see that as at issue.

I can only ask that you try again; and if the behaviour persists on your side, please zip up and send me a copy of what you are compiling. But I am getting a list from using your document patch, as you can see.

**Comment by opoudjis** [comment]
@jerstlouis Reminder. As I cannot replicate this behaviour, I will need you to re-attempt it, and zip up and send me a copy of what you are getting if it persists.
